import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { transformAsync } from '@babel/core';
import { JSDOM } from 'jsdom';
import React, { act } from 'react';
const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost'});
globalThis.window=dom.window;globalThis.document=dom.window.document;globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let change, command;
const snapshot={game:{id:'g',code:'ABC123',status:'question',currentQuestion:'q'},position:1,total:2,serverNow:Date.now(),deadline:Date.now()+20000,question:{id:'q',text:'Capital?',options:['Paris','Rome']},players:[{id:'p',nickname:'Ada',score:0}],me:{id:'p',answer:null},answerCount:0};
globalThis.__gameTest={React,pb:{},watchGame:(_pb,_g,_s,callback)=>{change=callback;callback(structuredClone(snapshot));return ()=>{};},sendGame:async(...args)=>{command=args;}};
let source=await readFile('src/components/LobbyPanel.jsx','utf8');
source=source.replace(/import .* from ['"](.*?)['"];?/g,(line,path)=>path==='react'?line.replace("'react'",JSON.stringify(import.meta.resolve('react'))):path.includes('pocketbase')?'const {pb}=globalThis.__gameTest;':'const {watchGame,sendGame}=globalThis.__gameTest;');
const {code}=await transformAsync(source,{plugins:[['@babel/plugin-transform-react-jsx',{runtime:'classic'}]],configFile:false,babelrc:false});
const {default:Panel}=await import(`data:text/javascript;base64,${Buffer.from('const React=globalThis.__gameTest.React;\n'+code).toString('base64')}`);
const {createRoot}=await import('react-dom/client');const root=createRoot(document.getElementById('root'));
test('player answers, sees receipt then results and leaderboard; host controls next and replay',async()=>{
 await act(async()=>root.render(React.createElement(Panel,{gameId:'g',session:{playerId:'p',token:'secret'}})));
 assert.match(document.body.textContent,/Capital\?/);
 const option=[...document.querySelectorAll('button')].find(b=>b.textContent.includes('Paris'));assert.ok(option);
 await act(async()=>option.click());assert.equal(command[2],'answer');assert.equal(command[3].optionIndex,0);assert.equal(command[3].token,'secret');
 const answered=structuredClone(snapshot);answered.me.answer={optionIndex:0};await act(async()=>change(answered));assert.match(document.body.textContent,/Answer received/);
 const result=structuredClone(answered);result.game.status='results';result.question.correctIndex=0;result.distribution=[1,0];result.me.answer={optionIndex:0,isCorrect:true,points:950};result.players[0].score=950;
 await act(async()=>change(result));assert.match(document.body.textContent,/Correct/);assert.match(document.body.textContent,/950/);
 await act(async()=>root.render(React.createElement(Panel,{gameId:'g',onReplay:()=>{command='replay';}})));await act(async()=>change(result));
 const next=[...document.querySelectorAll('button')].find(b=>b.textContent==='Next question');assert.ok(next);await act(async()=>next.click());assert.equal(command[3].action,'next');
 result.game.status='finished';await act(async()=>change(result));const replay=[...document.querySelectorAll('button')].find(b=>b.textContent==='Play again');assert.ok(replay);await act(async()=>replay.click());assert.equal(command,'replay');
 await act(async()=>root.unmount());
});
